services:
    base.composer_reader:
         class: BaseBundle\Services\ComposerReaderService
         arguments: ["%kernel.root_dir%"]

    base.task_manager:
         class: BaseBundle\Services\TaskService
         arguments: ["%beanstalkd_host%","%beanstalkd_port%"]

    base.preferences:
         class: BaseBundle\Services\PreferenceService
         arguments: ["@doctrine.orm.entity_manager"]

#    base.locale_listener:
#        class: BaseBundle\EventListener\LocaleListener
#        arguments: ["%kernel.default_locale%"]
#        tags:
#            - { name: kernel.event_subscriber }

    base.twig.database_preferences_extension:
         class: BaseBundle\Twig\Extension\DatabasePreferencesExtension
         lazy: true
         arguments: ["@base.preferences"]
         tags:
             - { name: twig.extension }

    base.twig.composer_reader_extension:
         class: BaseBundle\Twig\Extension\ComposerReaderExtension
         lazy: true
         arguments: ["@base.composer_reader"]
         tags:
             - { name: twig.extension }
    base.form.type.name:
        class: BaseBundle\Form\Type\NameType
        tags:
            - { name: form.type, alias: name }

    base.form.type.variables:
        class: BaseBundle\Form\Type\VariablesType
        tags:
            - { name: form.type, alias: variables }

#    base.admin.contentblock:
#        class: BaseBundle\Admin\ContentBlockAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Content",label_catalogue: "messages",  label: "Content Block" }
#        arguments:
#            - ~
#            - BaseBundle\Entity\ContentBlock
#            - BaseBundle:ContentBlockAdmin
#
#    base.admin.preference:
#        class: BaseBundle\Admin\PreferenceAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, show_in_dashboard: true,  group: "Settings", label_catalogue: "messages",label: "Preferences"}
#        arguments:
#            - ~
#            - BaseBundle\Entity\Preference
#            - ~
